@startuml
main -> ExportateurSourcePlantUML : exporterDiagramme(GestionnaireClasses)
ExportateurSourcePlantUML -> GestionnaireClasses : getClasses()
GestionnaireClasses --> ExportateurSourcePlantUML : List<Classe>

Loop pour chaque classe
    ExportateurSourcePlantUML -> ExportateurSourcePlantUML : exporterClasse(classe)
    ExportateurSourcePlantUML -> Classe : getNom()
    Classe --> ExportateurSourcePlantUML : String
    ExportateurSourcePlantUML -> Classe : getAttributs(classe)
    Classe --> ExportateurSourcePlantUML : List<Attribut>

    Loop pour chaque attribut
        ExportateurSourcePlantUML -> Attribut : getAcces()
        Attribut --> ExportateurSourcePlantUML : int
        ExportateurSourcePlantUML -> ExportateurSourcePlantUML : getSymbole(int)
        ExportateurSourcePlantUML -> Attribut : getNom()
        Attribut --> ExportateurSourcePlantUML : String
        ExportateurSourcePlantUML -> Attribut : getType()
        Attribut --> ExportateurSourcePlantUML : Class
    end

    ExportateurSourcePlantUML -> Classe : getMethode()
    Classe --> ExportateurSourcePlantUML : List<Methode>

    Loop pour chaque methode
    ExportateurSourcePlantUML -> Methode : getAcces()
    Methode --> ExportateurSourcePlantUML : int
    ExportateurSourcePlantUML -> ExportateurSourcePlantUML : getSymbole(int)
    ExportateurSourcePlantUML -> Methode : getNom()
    Methode --> ExportateurSourcePlantUML : String
    end
end

@enduml